spring.application.name=productapp
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/api-doc